/**
 * GENERATED by scripts/build-audio-sprite.mjs - do not edit by hand.
 *
 * One audio sprite per narrated lesson (walkthrough.mp3): all segments back
 * to back in one file, so the player never swaps src on its audio element.
 * Swapping src is what broke narration after the first segment on iOS
 * Safari (Guy, 13 Sep 15:56 IDT: only the intro played, the rest fell back
 * to silent text) - WebKit treats a new src outside a user gesture as a new
 * media load and blocks play(). Seeking one blessed element is safe
 * everywhere. Offsets/durations are ffprobe-measured from the per-segment
 * source mp3s, in play order.
 */
export interface SpriteTiming {
  /** Segment start inside the sprite, milliseconds. */
  offsetMs: number;
  /** Segment length, milliseconds. */
  durationMs: number;
}

export interface LessonSprite {
  spriteFile: string;
  /** Keyed by segment id (intro, step-1, step-2, ...), in play order. */
  segments: Record<string, SpriteTiming>;
}

export const LESSON_SPRITES: Record<string, LessonSprite> = {
  "lesson-0-meet-the-chart": {
    "spriteFile": "walkthrough.mp3",
    "segments": {
      "intro": {
        "offsetMs": 0,
        "durationMs": 14448
      },
      "step-1": {
        "offsetMs": 14448,
        "durationMs": 6120
      },
      "step-2": {
        "offsetMs": 20568,
        "durationMs": 5448
      },
      "step-3": {
        "offsetMs": 26016,
        "durationMs": 5856
      }
    }
  }
};
