export type BoardState = 'Ready' | 'Doing' | 'Review' | 'Blocked' | 'Done';
export type BoardCard = {
  id: string; epic: string; pillar: 'Product Development' | 'Design / UX' | 'Content' | 'Business Development' | 'Platform / Operations';
  title: string; state: BoardState; why: string; outcome: string; evidence: string; gate: string; owner: string; priority: string; blocker: string;
};

// Controller export. The operating controller updates this snapshot only after
// reading back the durable Todos and their source-linked evidence. /ops renders
// this same model; it does not maintain a second UI-only task list.
export const boardSnapshot = {
  verifiedAt: '2026-09-24T05:32:00.000Z',
  source: 'Tikerino durable Todos + four-pillar controller evidence',
  queues: ['Ready', 'Doing', 'Review', 'Blocked', 'Done'] as BoardState[],
  pillars: ['Product Development', 'Design / UX', 'Content', 'Business Development', 'Platform / Operations'] as const,
  cards: [
    {id:'todo-01M3202AWF6540PJ69J1RSEPH2',epic:'Living Chart release',pillar:'Product Development',title:'Ship the complete Living Chart first lesson loop',state:'Done',why:'Guy chose merge now (23/9 20:52), with the progress-loss fix as the next P0 before any outside learner.',outcome:'Lessons become candles; completion awards +25 exactly once, returning learners keep credit for lessons they already finished, and no unapproved Safe Floor appears.',evidence:'PR #9 merged f8c6258; Railway 6621855619 success; production smoke 59/59 at 390px, axe clean: fresh learner 0→25, seeded legacy learner keeps 25, no Safe Floor.',gate:'Done.',owner:'Product Development',priority:'P0 · rank 1',blocker:'None'},
    {id:'todo-01M36FR4E65XH334H72CSJ6EAP',epic:'Living Chart release',pillar:'Product Development',title:'Stop progress from being lost when two tabs are open or a save fails',state:'Done',why:'A stale tab or failed write could silently wipe or falsely claim earned progress; gate before any outside learner.',outcome:'Saves merge stored progress first (lessonAwards and answers as ledgers) and a failed save is surfaced instead of claiming +XP.',evidence:'PR #15 merged 667a1b9; Railway 6622236978 success; production smoke 65/65 at 390px, axe clean. Caveat: "+25 not recorded after failed save" proven by unit test only; E2E proves the failure is surfaced with no +XP claim.',gate:'Done.',owner:'Product Development',priority:'P0',blocker:'None'},
    {id:'todo-01M37TZ518JX5HK6180V533XJ6',epic:'Living Chart release',pillar:'Product Development',title:'Fix the reveal +0 XP pill and the logged a11y follow-ups',state:'Done',why:'The pill contradicted the exercise points under it on the live loop.',outcome:'The reveal shows one consistent XP number and focus order matches reading order.',evidence:'PR #17 merged 0787b4e; Railway 6627626628 success; 390px production smoke, axe clean.',gate:'Done.',owner:'Repo worker',priority:'P1',blocker:'None'},
    {id:'todo-01M3202DDRG78NQBZ41Y8G37CN',epic:'Living Chart release',pillar:'Product Development',title:'Queue offline lesson work and credit it only once',state:'Done',why:'Offline retries must not create false progress or duplicate credit.',outcome:'Queued work is neutral, reconnect confirms it, and server-confirmed work updates progression once.',evidence:'PR #18 merged d31e0a5; Railway 6629113289 success; offline/reconnect, duplicate flush and zero-XP-before-confirmation checks green in production smoke.',gate:'Done.',owner:'Repo worker',priority:'P1',blocker:'None'},
    {id:'todo-01M3202FJK5MV9NQ67EWKQD8GW',epic:'Retention and recovery',pillar:'Product Development',title:'Make returns after a missed day feel like recovery',state:'Done',why:'Persistence and recovery were absent from the live journey.',outcome:'A missed day restarts the run without removing XP or mastery; lifetime practice stays visible.',evidence:'PR #19 merged 0aa8913; Railway 6629239475 success; production smoke 92/92, axe clean. Ladder-free; ladder values pending Guy.',gate:'Done.',owner:'Repo worker',priority:'P1',blocker:'None'},
    {id:'todo-01M38P1X83R7GB0MMRTT7Z7APP',epic:'Retention and recovery',pillar:'Product Development',title:'Award the daily practice +10 XP once per local day',state:'Done',why:'Guy approved +10 daily practice on 19/9 14:38.',outcome:'The first server-confirmed answer each local day adds +10 once, per day not per device, shown on the chart and in the HUD.',evidence:'PR #20 merged 702efe1; Railway 6629378652 success; production smoke 95/95 at 390px, axe clean; DST, two-device merge and XP-monotonic tests green. No streak bonus, no backfill.',gate:'Done.',owner:'Repo worker',priority:'P1',blocker:'None'},
    {id:'todo-01M2GNBC42PBHTPQ6KGWZSZZA3',epic:'Living Chart release',pillar:'Product Development',title:'Set the accessibility release bar and prove every live screen meets it',state:'Done',why:'The MVP loop is feature-complete and the audience is 13+; axe passed but nothing manual had been checked.',outcome:'WCAG 2.2 AA bar (IS 5568 as LEGAL-IL leads), screen inventory and per-screen matrix; P0 focus fixes live.',evidence:'PR #22 merged fa0ca54; Railway 6630879544 success; production smoke 95/95 and production audit 21/21 screens pass, axe 2.2 AA clean. Device VoiceOver/TalkBack still unverified.',gate:'Done; controller approved the bar and matrix.',owner:'Repo worker',priority:'P1',blocker:'None'},
    {id:'todo-01M38XXFJGZ3DDYA642TMR0RTQ',epic:'Living Chart release',pillar:'Product Development',title:'Close the accessibility audit gaps',state:'Doing',why:'The first audit did not reach pick-the-candle or the path with a queued answer.',outcome:'Every inventoried learner state is in the audited matrix.',evidence:'Matrix regenerated with the missing states; PR with checks green.',gate:'PR checks green, merge.',owner:'Repo worker',priority:'P1 · WIP 1',blocker:'None'},
    {id:'todo-01M38XXG9Y5KH346TJCA8JVEC8',epic:'Living Chart release',pillar:'Product Development',title:'Run VoiceOver and TalkBack on the core loop on a real phone',state:'Blocked',why:'AX-tree transcripts show what screen readers get, not how they speak it.',outcome:'Device screen-reader notes for onboarding to reveal and back.',evidence:'Needs a phone; about 10 minutes.',gate:'Guy-owned.',owner:'Guy',priority:'P1 evidence',blocker:'Needs a device run'},
    {id:'todo-01M38XXFSE63CH72NHR5V8Z46W',epic:'Living Chart release',pillar:'Product Development',title:'Measure chart candle contrast (WCAG 1.4.11)',state:'Ready',why:'Candle marks are checked by eye, not measured.',outcome:'Every candle, wick and volume bar meets 3:1 against its background, measured.',evidence:'Measured ratios in the matrix.',gate:'PR review.',owner:'Repo worker',priority:'P1 backlog',blocker:'None'},
    {id:'todo-01M38XXG0DJDDP47M80DXCZABW',epic:'Living Chart release',pillar:'Product Development',title:'Announce each onboarding step to screen readers',state:'Ready',why:'Focus stays on Next and the new step text is not announced.',outcome:'Each step change is announced.',evidence:'Audit focus/announce check.',gate:'PR review.',owner:'Repo worker',priority:'P2',blocker:'None'},
    {id:'todo-01M38WZE8ANNG0BBTHBNAXN44Z',epic:'Retention and recovery',pillar:'Product Development',title:'Approve persistence ladder values (proposed 19/9: +2/day from day 2, cap +20, max +30)',state:'Blocked',why:'Guy asked for a persistence bonus on 19/9; the proposed values have no answer yet.',outcome:'Guy approves or changes the ladder values before any ladder code ships.',evidence:'Proposal sent to Guy 19/9 14:47; no reply.',gate:'Guy-owned gate.',owner:'Guy',priority:'P1 gate',blocker:'Awaiting Guy'},
    {id:'todo-01M38WZEHJGE9J1D3Q156V9V2C',epic:'Living Chart experience contract',pillar:'Design / UX',title:'Copy pass: "0 days" HUD pill after a gap, and "+10 XP" vs the legacy score of 12',state:'Ready',why:'After a missed day the run pill reads "0 days"; the reveal +10 XP pill (unlabeled for screen readers too) sits above the legacy exercise score of 12.',outcome:'Recovery-friendly run copy and a clearly different, labeled daily XP.',evidence:'#19/#20 return-after-gap screens, #20 reveal screenshot, #22 reveal transcript.',gate:'Design copy, then a small Dev change.',owner:'Design / UX',priority:'Small copy',blocker:'None'},
    {id:'todo-01M31ZMMB8CSYRXX1NNHXBW2EQ',epic:'Living Chart release',pillar:'Product Development',title:'Regenerate the approved Living Chart source package',state:'Done',why:'The original exact Markdown bytes were unavailable and must not be counterfeited.',outcome:'Engineering has a newly versioned portable candidate with all 11 sections and four tables.',evidence:'Fresh SHA-256, drift report, clean link and diff checks, and independent patch application.',gate:'Use the reviewed package in the repository change.',owner:'Engineering',priority:'P0 enablement',blocker:'None'},
    {id:'todo-01M31ZQQQ7H4X2Q1VRS59WZJ32',epic:'Living Chart experience contract',pillar:'Design / UX',title:'Define every learner-visible Living Chart state',state:'Done',why:'Code must not invent Safe Floor or mastery rules.',outcome:'Engineering has one contract for home, forming candle, gates, offline, reveal, recovery, persistence, mastery and exam states.',evidence:'Accepted state/component specification and acceptance matrix.',gate:'Use the completed curriculum package as input to the next proposal.',owner:'Design / UX',priority:'Completed P0 evidence',blocker:'None'},
    {id:'todo-01M31ZPW17QEDAXQW577944M2S',epic:'Curriculum architecture',pillar:'Content',title:'Map what each course unit requires, teaches, practices and proves',state:'Done',why:'Production must not harden unresolved choices or omit prerequisites and assessment evidence.',outcome:'Every draft unit has a stable ID, prerequisites, objective, practice, unseen assessment, simulator tier and accessibility route.',evidence:'28 stable IDs, acyclic spine, S0-S3 tiers, both options, dissent areas and owner choices visible.',gate:'Use the accepted matrix to create both curriculum maps.',owner:'Content',priority:'P0 evidence',blocker:'Curriculum option and proficiency thresholds remain open'},
    {id:'todo-01M2XAB2VC7HXRGSG2YTWN9D68',epic:'Curriculum architecture',pillar:'Content',title:'Ratify syllabus v2',state:'Review',why:'The v2 curriculum map folds in Guy’s G1–G4 decisions and Claude findings 1–18.',outcome:'Guy ratifies one syllabus that Design and Business Development can rebase onto.',evidence:'Supersedes v1 Package SHA 85fc8249. v2 curriculum map delivered to Guy 23/9 22:18; G1–G4 plus Claude findings 1–18; structural validator 0 issues.',gate:'Guy-owned gate: ratify syllabus v2.',owner:'Guy',priority:'P0 review',blocker:'Not ratified'},
    {id:'todo-01M2WCD20X2WWDKJQFRQJSEQ2C',epic:'Living Chart experience contract',pillar:'Design / UX',title:'Review the Safe Floor, mastery and module-exam proposal',state:'Review',why:'The proposal connects the curriculum to learner-visible progression.',outcome:'One decision-ready proposal connects the syllabus to learner-visible progression without inventing curriculum policy.',evidence:'Proposal v2.1 SHA 58d2bb06; Guy 19/9 rules confirm +25/+10/+40/+150 and zero XP loss; MVP assessments are multiple choice only, auto-graded (Guy 23/9 20:54).',gate:'Controller review of v2.1, then bring only the open choices to Guy.',owner:'Design / UX',priority:'P0 review',blocker:'Syllabus v2 ratification still open'},
    {id:'todo-01M320KF1J6FSPK4YAP5C6ZP9Y',epic:'Market-position validation',pillar:'Business Development',title:'Prepare neutral no-contact validation packets for both positions',state:'Done',why:'Scorecards needed non-leading instruments before any external contact.',outcome:'Each branch has a screener, neutral prompts, evidence form and exact scorecard rubric.',evidence:'Two verified packets; leading-language review passed; no participant data, outreach or spend.',gate:'BD adapts these after curriculum, then brings one decision-ready audience/method/consent approval to Guy.',owner:'Business Development',priority:'Completed P0 evidence',blocker:'Current owner is BD; depends on Content maps and curriculum decision, not Guy now'},
    {id:'todo-01M2WKGEEYR8EMS63Z7CK64VX6',epic:'Market-position validation',pillar:'Business Development',title:'Review audience, method and consent validation package',state:'Review',why:'The package covers 13+ learners and the Israeli legal entity.',outcome:'One decision-ready approval names the audience, neutral method and consent boundary without starting outreach.',evidence:'Package v1.1 SHA 54b1fa20; Guy 23/9: 13+ teenagers in scope, Israeli legal entity.',gate:'Controller review of v1.1 before asking Guy.',owner:'Business Development',priority:'P0 review',blocker:'Syllabus v2 ratification still open; no outreach, recruitment, analytics, deposits, marketing or spend'},
    {id:'todo-01M31ZPXKMEX9C3D4JFJX717EV',epic:'Shared internal model panel',pillar:'Platform / Operations',title:'Enable attributed four-model review without exposing API keys',state:'Doing',why:'Projects need a small neutral fan-out service, not a product-owned research pipeline.',outcome:'One internal endpoint returns four attributed raw outputs and one synthesis without owning project logic.',evidence:'Neutral local service commit b9e2770; no product imports, DB, queue, web research, RAG or Drive.',gate:'Choose a neutral repository and deployment destination before publishing.',owner:'Platform / Operations',priority:'Platform capability',blocker:'Neutral destination not selected'},
    {id:'todo-01M32BFG73P1Y7AK3P8T5XGJYY',epic:'Private operating surface',pillar:'Platform / Operations',title:'Put the project-management board inside private /ops',state:'Doing',why:'Guy confirmed the existing-client /ops fix and asked for the operating board in the same private app.',outcome:'Owner-only /ops contains whole-project and per-pillar views, Epics and the five approved queues.',evidence:'Mobile visual, owner boundary, PWA controller/cache, reload and existing-client checks.',gate:'Deploy, verify on production and ask Guy to inspect the same iPhone.',owner:'Platform / Operations',priority:'P0 current',blocker:'None'},
    {id:'todo-01M32A3KQY6T3WM3WKBH0J9MD5',epic:'Private operating surface',pillar:'Platform / Operations',title:'Release installed learner workers from /ops',state:'Done',why:'An old root worker intercepted the new private route on Guy’s iPhone.',outcome:'Existing clients migrate automatically and /ops reaches owner auth without cache clearing.',evidence:'Deterministic old-worker upgrade harness, green CI, live worker denylist/migration and Guy confirmed “works”.',gate:'Keep regression coverage with every root-worker change.',owner:'Platform / Operations',priority:'Completed production fix',blocker:'None'},
    {id:'todo-01M36F7NPFR2E4ZRZARB5Q2XW1',epic:'Parallel delivery',pillar:'Platform / Operations',title:'Let two agents build Tikerino side by side without colliding',state:'Done',why:'Guy approved parallel lanes on 23/9 so delivery speed is not capped at one agent.',outcome:'Two scripted worktree lanes, one child per lane, merged one at a time through protected main.',evidence:'PR #11 guide and script; branch protection requires both CI checks and up-to-date branches; pilot PRs #12 and #13 merged in sequence after a refused out-of-date merge and a rebase; main 4e44fcc green.',gate:'Second agent: Antigravity trial if Guy approves, otherwise Claude from 1/10.',owner:'Platform / Operations',priority:'Platform capability',blocker:'None for the lanes; Gemini CLI free path closed by Google'}
  ] satisfies BoardCard[]
};
