export type BoardState = 'Ready' | 'Doing' | 'Review' | 'Blocked' | 'Done';
export type BoardCard = {
  id: string; epic: string; pillar: 'Product Development' | 'Design / UX' | 'Content' | 'Business Development' | 'Platform / Operations';
  title: string; state: BoardState; why: string; outcome: string; evidence: string; gate: string; owner: string; priority: string; blocker: string;
};

// Controller export. The operating controller updates this snapshot only after
// reading back the durable Todos and their source-linked evidence. /ops renders
// this same model; it does not maintain a second UI-only task list.
export const boardSnapshot = {
  verifiedAt: '2026-09-23T08:38:00.000Z',
  source: 'Tikerino durable Todos + four-pillar controller evidence',
  queues: ['Ready', 'Doing', 'Review', 'Blocked', 'Done'] as BoardState[],
  pillars: ['Product Development', 'Design / UX', 'Content', 'Business Development', 'Platform / Operations'] as const,
  cards: [
    {id:'todo-01M3202AWF6540PJ69J1RSEPH2',epic:'Living Chart release',pillar:'Product Development',title:'Merge the complete Living Chart lesson loop once the second review clears',state:'Review',why:'Claude found two blockers in PR #9; both are fixed and verified, so only the OpenAI review stands between this and learners.',outcome:'Lessons become candles; completion awards +25 exactly once, returning learners keep credit for lessons they already finished, and no unapproved Safe Floor appears.',evidence:'PR #9 at aca46ca; Claude (claude-opus-5-5): safe after required fixes; B1 legacy backfill and B2 Safe Floor removal fixed and checked against the diff; 192 tests pass; both required CI checks green; seeded-legacy 390x844 loop shows 25 XP.',gate:'OpenAI review (model unverified, relayed by Guy), then update from main, re-run CI and merge; confirm production.',owner:'Product Development',priority:'P0 · rank 1',blocker:'OpenAI verdict pending'},
    {id:'todo-01M3202DDRG78NQBZ41Y8G37CN',epic:'Living Chart release',pillar:'Product Development',title:'Queue offline lesson work and credit it only once',state:'Ready',why:'Offline retries must not create false progress or duplicate credit.',outcome:'Queued work is neutral, reconnect confirms it, and server-confirmed work updates progression once.',evidence:'Offline/reconnect test; duplicate flush; zero XP before confirmation; text and reduced-motion parity.',gate:'Start after the first Living Chart loop.',owner:'Controller',priority:'P1 · rank 2',blocker:'First loop and authoritative response contract'},
    {id:'todo-01M3202FJK5MV9NQ67EWKQD8GW',epic:'Retention and recovery',pillar:'Product Development',title:'Make returns after a missed day feel like recovery',state:'Ready',why:'Persistence and recovery are absent from the live journey.',outcome:'A missed day restarts the run without removing XP or mastery; lifetime practice stays visible.',evidence:'Exact ladder tests; deterministic day boundary; XP monotonic property; return-after-gap visual and text evidence.',gate:'Start after the first loop; decide day authority only if state becomes shared.',owner:'Controller',priority:'P1 · rank 3',blocker:'None for local deterministic state'},
    {id:'todo-01M31ZMMB8CSYRXX1NNHXBW2EQ',epic:'Living Chart release',pillar:'Product Development',title:'Regenerate the approved Living Chart source package',state:'Done',why:'The original exact Markdown bytes were unavailable and must not be counterfeited.',outcome:'Engineering has a newly versioned portable candidate with all 11 sections and four tables.',evidence:'Fresh SHA-256, drift report, clean link and diff checks, and independent patch application.',gate:'Use the reviewed package in the repository change.',owner:'Engineering',priority:'P0 enablement',blocker:'None'},
    {id:'todo-01M31ZQQQ7H4X2Q1VRS59WZJ32',epic:'Living Chart experience contract',pillar:'Design / UX',title:'Define every learner-visible Living Chart state',state:'Done',why:'Code must not invent Safe Floor or mastery rules.',outcome:'Engineering has one contract for home, forming candle, gates, offline, reveal, recovery, persistence, mastery and exam states.',evidence:'Accepted state/component specification and acceptance matrix.',gate:'Use the completed curriculum package as input to the next proposal.',owner:'Design / UX',priority:'Completed P0 evidence',blocker:'None'},
    {id:'todo-01M31ZPW17QEDAXQW577944M2S',epic:'Curriculum architecture',pillar:'Content',title:'Map what each course unit requires, teaches, practices and proves',state:'Done',why:'Production must not harden unresolved choices or omit prerequisites and assessment evidence.',outcome:'Every draft unit has a stable ID, prerequisites, objective, practice, unseen assessment, simulator tier and accessibility route.',evidence:'28 stable IDs, acyclic spine, S0-S3 tiers, both options, dissent areas and owner choices visible.',gate:'Use the accepted matrix to create both curriculum maps.',owner:'Content',priority:'P0 evidence',blocker:'Curriculum option and proficiency thresholds remain open'},
    {id:'todo-01M2XAB2VC7HXRGSG2YTWN9D68',epic:'Curriculum architecture',pillar:'Content',title:'Review the curriculum decision package',state:'Review',why:'Both curriculum options, comparison and measurable gate are complete and need independent challenge before ratification.',outcome:'Guy receives one attributed verdict matrix with disagreements preserved, not a majority-vote rewrite.',evidence:'Package SHA 85fc8249; Option 1 has 28 modules/176 titles; Option 2 has 24/209; structural validator reports zero issues. First Claude relay arrived without the files; the package was re-sent 23/9 09:29.',gate:'Claude review of the re-sent package; OpenAI review pending. Reconcile verdicts before the owner decision.',owner:'Content controller',priority:'P0 review',blocker:'Independent reviews pending; package not ratified'},
    {id:'todo-01M2WCD20X2WWDKJQFRQJSEQ2C',epic:'Living Chart experience contract',pillar:'Design / UX',title:'Review the Safe Floor, mastery and module-exam proposal',state:'Review',why:'The proposal is written; it must survive the curriculum reviews before Guy sees the open choices.',outcome:'One decision-ready proposal connects Option 1 to learner-visible progression without inventing curriculum policy.',evidence:'Proposal SHA 78ba5c7b: server-confirmed floor locks, +40 mastery once per skill after unseen transfer, +150 module exam once, proficiency badge without new XP. Guy’s 19/9 rules confirm +25/+10/+40/+150 and zero XP loss.',gate:'Reconcile curriculum reviews, then bring only the open choices to Guy: floor formula, mastery threshold, exam semantics, capstone XP, gate thresholds and persistence ladder values.',owner:'Design / UX',priority:'P0 review',blocker:'Curriculum reviews pending; nothing ships to learners until Guy decides'},
    {id:'todo-01M320KF1J6FSPK4YAP5C6ZP9Y',epic:'Market-position validation',pillar:'Business Development',title:'Prepare neutral no-contact validation packets for both positions',state:'Done',why:'Scorecards needed non-leading instruments before any external contact.',outcome:'Each branch has a screener, neutral prompts, evidence form and exact scorecard rubric.',evidence:'Two verified packets; leading-language review passed; no participant data, outreach or spend.',gate:'BD adapts these after curriculum, then brings one decision-ready audience/method/consent approval to Guy.',owner:'Business Development',priority:'Completed P0 evidence',blocker:'Current owner is BD; depends on Content maps and curriculum decision, not Guy now'},
    {id:'todo-01M2WKGEEYR8EMS63Z7CK64VX6',epic:'Market-position validation',pillar:'Business Development',title:'Review audience, method and consent validation package',state:'Review',why:'The recommended portfolio-first structure now allows positioning and validation mechanics to be revised.',outcome:'One decision-ready approval names the audience, neutral method and consent boundary without starting outreach.',evidence:'Provisional package SHA f8e26789: audience 18–40 with real intent; 6 problem interviews + 6 concept sessions; H1–H5 gates; separate consent.',gate:'Reconcile curriculum reviews, then review the linked audience, positioning, method and consent choices before asking Guy.',owner:'Business Development',priority:'P0 review',blocker:'No outreach, recruitment, analytics, deposits, marketing or spend; curriculum recommendation remains provisional'},
    {id:'todo-01M31ZPXKMEX9C3D4JFJX717EV',epic:'Shared internal model panel',pillar:'Platform / Operations',title:'Enable attributed four-model review without exposing API keys',state:'Doing',why:'Projects need a small neutral fan-out service, not a product-owned research pipeline.',outcome:'One internal endpoint returns four attributed raw outputs and one synthesis without owning project logic.',evidence:'Neutral local service commit b9e2770; no product imports, DB, queue, web research, RAG or Drive.',gate:'Choose a neutral repository and deployment destination before publishing.',owner:'Platform / Operations',priority:'Platform capability',blocker:'Neutral destination not selected'},
    {id:'todo-01M32BFG73P1Y7AK3P8T5XGJYY',epic:'Private operating surface',pillar:'Platform / Operations',title:'Put the project-management board inside private /ops',state:'Doing',why:'Guy confirmed the existing-client /ops fix and asked for the operating board in the same private app.',outcome:'Owner-only /ops contains whole-project and per-pillar views, Epics and the five approved queues.',evidence:'Mobile visual, owner boundary, PWA controller/cache, reload and existing-client checks.',gate:'Deploy, verify on production and ask Guy to inspect the same iPhone.',owner:'Platform / Operations',priority:'P0 current',blocker:'None'},
    {id:'todo-01M32A3KQY6T3WM3WKBH0J9MD5',epic:'Private operating surface',pillar:'Platform / Operations',title:'Release installed learner workers from /ops',state:'Done',why:'An old root worker intercepted the new private route on Guy’s iPhone.',outcome:'Existing clients migrate automatically and /ops reaches owner auth without cache clearing.',evidence:'Deterministic old-worker upgrade harness, green CI, live worker denylist/migration and Guy confirmed “works”.',gate:'Keep regression coverage with every root-worker change.',owner:'Platform / Operations',priority:'Completed production fix',blocker:'None'},
    {id:'todo-01M36F7NPFR2E4ZRZARB5Q2XW1',epic:'Parallel delivery',pillar:'Platform / Operations',title:'Let two agents build Tikerino side by side without colliding',state:'Done',why:'Guy approved parallel lanes on 23/9 so delivery speed is not capped at one agent.',outcome:'Two scripted worktree lanes, one child per lane, merged one at a time through protected main.',evidence:'PR #11 guide and script; branch protection requires both CI checks and up-to-date branches; pilot PRs #12 and #13 merged in sequence after a refused out-of-date merge and a rebase; main 4e44fcc green.',gate:'Second agent: Antigravity trial if Guy approves, otherwise Claude from 1/10.',owner:'Platform / Operations',priority:'Platform capability',blocker:'None for the lanes; Gemini CLI free path closed by Google'}
  ] satisfies BoardCard[]
};
