import { createHmac, timingSafeEqual } from 'node:crypto';
import formbody from '@fastify/formbody';
import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';

const COOKIE = 'tikerino_ops';
const TTL_MS = 12 * 60 * 60 * 1000;
const safeEqual = (a: string, b: string) => { const x=Buffer.from(a), y=Buffer.from(b); return x.length===y.length && timingSafeEqual(x,y); };
const sign = (value: string, secret: string) => createHmac('sha256',secret).update(value).digest('base64url');
function cookie(req: FastifyRequest) { const raw=req.headers.cookie??''; return raw.split(';').map(v=>v.trim()).find(v=>v.startsWith(`${COOKIE}=`))?.slice(COOKIE.length+1); }
function authorized(req: FastifyRequest, secret: string) { const c=cookie(req); if(!c)return false; const [expires,sig]=c.split('.'); if(!expires||!sig||Number(expires)<Date.now())return false; return safeEqual(sig,sign(expires,secret)); }
function security(reply: FastifyReply) { reply.header('Cache-Control','private, no-store').header('X-Frame-Options','DENY').header('X-Content-Type-Options','nosniff').header('Referrer-Policy','no-referrer').header('Content-Security-Policy',"default-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'"); }
function login(error='') { return `<!doctype html><html lang="en"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0b1220"><title>Tikerino Ops sign in</title><style>${css}</style><main class="login"><section><div class="brand">TIKERINO / OPS</div><h1>Owner sign in</h1><p>Private operating surface. Session expires after 12 hours.</p>${error?'<p class="bad">Incorrect password.</p>':''}<form method="post" action="/ops/login"><label>Password<input type="password" name="password" autocomplete="current-password" required autofocus></label><button>Sign in</button></form></section></main></html>`; }
function dashboard(now: string) { return `<!doctype html><html lang="en"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0b1220"><link rel="manifest" href="/ops/manifest.webmanifest"><title>Tikerino Operations</title><style>${css}</style><header><div class="brand">TIKERINO / OPS</div><form method="post" action="/ops/logout"><button class="quiet">Sign out</button></form></header><main><div class="eyebrow">PRIVATE CONTROL SURFACE</div><h1>Operations</h1><p id="state">Live snapshot <time>${now}</time></p><div class="grid"><section><b>Production</b><strong class="ok">Online</strong><span>tikerino.com</span></section><section><b>Data boundary</b><strong>Postgres</strong><span>No silent file fallback</span></section><section><b>Release source</b><strong>Reconciled</strong><span>Commit shown by deployed build</span></section><section><b>PWA</b><strong>Ready</strong><span>Private shell and offline snapshot</span></section></div><section class="note"><b>Offline behavior</b><p>The last authenticated operations snapshot is available on this device. The timestamp above is the moment it was loaded, not a claim of current production state.</p></section><p class="offline" id="offline" hidden>Offline snapshot. Reconnect to refresh.</p></main><script>if('serviceWorker'in navigator)navigator.serviceWorker.register('/ops/sw.js',{scope:'/ops/'});function net(){document.querySelector('#offline').hidden=navigator.onLine;document.querySelector('#state').className=navigator.onLine?'':'stale'}addEventListener('online',net);addEventListener('offline',net);net();</script></html>`; }
const css=`*{box-sizing:border-box}body{margin:0;background:#070c16;color:#e8edf5;font:15px system-ui,sans-serif}header{display:flex;justify-content:space-between;align-items:center;padding:18px 20px;border-bottom:1px solid #233049}.brand,.eyebrow{letter-spacing:.13em;font-size:12px;color:#7dd3fc}main{max-width:760px;margin:auto;padding:34px 20px}h1{font-size:36px;margin:.35em 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:28px 0}.grid section,.note,.login section{padding:20px;border:1px solid #27344c;border-radius:16px;background:#0d1626}.grid b,.grid span{display:block;color:#9cabbe}.grid strong{display:block;font-size:22px;margin:12px 0}.ok{color:#34d399}.note{margin-top:12px}.offline,.bad,.stale{color:#fbbf24}.login{min-height:100vh;display:grid;place-items:center}.login section{width:min(100%,420px)}label{display:grid;gap:8px;margin:24px 0}input,button{font:inherit;border-radius:9px;border:1px solid #34445f;padding:12px;background:#111d31;color:white}button{background:#2563eb;border:0;font-weight:700}.quiet{background:#172236}@media(max-width:560px){.grid{grid-template-columns:1fr}h1{font-size:32px}}`;
export function registerOps(app: FastifyInstance) {
 app.register(formbody);
 const password=process.env.OPS_PASSWORD?.trim(), secret=process.env.OPS_SESSION_SECRET?.trim();
 const configured=()=>Boolean(password&&secret&&secret.length>=32);
 app.get('/ops',async(req,reply)=>{security(reply);if(!configured())return reply.code(503).type('text/html').send('Operations is not configured.');if(!authorized(req,secret!))return reply.code(401).type('text/html').send(login());return reply.type('text/html').send(dashboard(new Date().toISOString()));});
 app.post('/ops/login',async(req,reply)=>{security(reply);if(!configured())return reply.code(503).send();const body=req.body as {password?:unknown}|undefined;const submitted=typeof body?.password==='string'?body.password:'';if(!safeEqual(submitted,password!))return reply.code(401).type('text/html').send(login('bad'));const expires=String(Date.now()+TTL_MS),value=`${expires}.${sign(expires,secret!)}`;reply.header('Set-Cookie',`${COOKIE}=${value}; Path=/ops; HttpOnly; Secure; SameSite=Strict; Max-Age=${TTL_MS/1000}`).redirect('/ops');});
 app.post('/ops/logout',async(_req,reply)=>{security(reply);reply.header('Set-Cookie',`${COOKIE}=; Path=/ops; HttpOnly; Secure; SameSite=Strict; Max-Age=0`).redirect('/ops');});
 app.get('/ops/manifest.webmanifest',async(req,reply)=>{security(reply);if(!configured()||!authorized(req,secret!))return reply.code(401).send({error:'unauthorized'});return reply.type('application/manifest+json').send({name:'Tikerino Operations',short_name:'Tikerino Ops',start_url:'/ops',scope:'/ops/',display:'standalone',background_color:'#070c16',theme_color:'#0b1220',icons:[{src:'/icons/icon-192.png',sizes:'192x192',type:'image/png'},{src:'/icons/icon-512.png',sizes:'512x512',type:'image/png'}]});});
 app.get('/ops/sw.js',async(req,reply)=>{security(reply);if(!configured()||!authorized(req,secret!))return reply.code(401).send('');return reply.type('application/javascript').send(`const C='tikerino-ops-v1';self.addEventListener('install',e=>e.waitUntil(caches.open(C).then(c=>c.add('/ops'))));self.addEventListener('activate',e=>e.waitUntil(self.clients.claim()));self.addEventListener('fetch',e=>{if(new URL(e.request.url).pathname!='/ops')return;e.respondWith(fetch(e.request).then(r=>{if(r.ok){const x=r.clone();caches.open(C).then(c=>c.put('/ops',x))}return r}).catch(()=>caches.match('/ops')))})`);});
}
